version: "3.7"

services:
  starbound:
    container_name: "starbound_server"
    build:
      context: ${SBPATH}
    volumes:
      - ./storage:/game/storage
      - ./mods:/game/mods
    image: "starbound_server"
    ports:
      - 21025:21025
